Use Jet;
CREATE TABLE Properties(
	PID bigint NOT NULL,
	MLSID varchar(30) NULL,
	MLSIDLabel varchar(20) NULL,
	Status varchar(20) NULL,
	Latitude decimal(9, 6) NULL,
	Longitude decimal(9, 6) NULL,
	Street varchar(200) NULL,
	City varchar(100) NULL,
	Zip varchar(10) NULL,
	State varchar(100) NULL,
	PropertyID bigint NULL,
	PropertyTypeID int NULL,
	ListingID bigint NULL,
	ListingTypeID int NULL,
	DataSourceID int NULL,
	MarketID int NULL,
	YearBuilt smallint NULL,
	SqFt smallint NULL,
	LotSize smallint NULL,
	Beds tinyint NULL,
	Baths decimal(3, 1) NULL,
	HOA decimal(12,4) NULL,
	Price decimal(12,4) NULL,
	PricePerSqFt decimal(12,4) NULL,
	AgentNotes text NULL,
	AgentName varchar(100) NULL,
	AgentTypeID int NULL,
	AgentID varchar(30) NULL,
	DOM int NULL,
	TaxAssessmentYear smallint NULL,
	TaxAssessment decimal(12,4) NULL,
	LastSoldDate date NULL,
	LastSoldPrice decimal(12,4) NULL,
	RentAmount decimal(12,4) NULL,
	RentLastUpdated date NULL,
	RentChangeDuration smallint NULL,
	RentChangeAmount decimal(12,4) NULL,
	RentValueLow decimal(12,4) NULL,
	RentValueHigh decimal(12,4) NULL,
	PriceEstimate decimal(12,4) NULL,
	PriceLastUpdated date NULL,
	PriceValueLow decimal(12,4) NULL,
	PriceValueHigh decimal(12,4) NULL,
	TaxRate decimal(5, 3) NULL,
	RegionID int NULL,
	RegionName varchar(100) NULL,
	RegionType varchar(50) NULL,
	NBHID int NULL,
	Photos text NULL,
	PhotosCount smallint NULL,
	MLSJson text NULL,
	PreviousListPrice decimal(12,4) NULL,
	ModificationTimestamp datetime NULL,
	OffMarketTimestamp datetime NULL,
	OnMarketTimestamp datetime NULL,
	OriginalEntryTimestamp datetime NULL,
	OriginatingSystemModificationTimestamp datetime NULL,
	PhotosChangeTimestamp datetime NULL,
	StatusChangeTimestamp datetime NULL,
	PreviousStandardStatus varchar(10) NULL,
	Yield decimal(5, 2) NULL,
	ReturnRate decimal(5, 2) NULL,
	JetScore int NULL,
	ListToARV decimal(5, 2) NULL,
	CapRate decimal(5, 2) NULL,
	PriceToRentRatio decimal(5, 2) NULL,
 CONSTRAINT PK_Properties_s PRIMARY KEY CLUSTERED 
(
	PID ASC
));
